version: '3'
services:
  app:
    environment:
      - DATABASE_URI=${DATABASE_URI}
      - PORT=${PORT}
    build:
      context: backend
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    volumes:
      - .:/app
