name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  DATABASE_URI: ${{ secrets.DATABASE_URI }}
  PORT: ${{ secrets.PORT }}

jobs:

  build:
    runs-on: [self-hosted]
    steps:
    - uses: actions/checkout@v3
    # - name: Setup Env Variables
      # run: export DATABASE_URI="${{ secrets.DATABASE_URI }}" & export PORT="${{ secrets.PORT }}"
    - name: Docker Compose
      run: docker-compose up -d --force-recreate --build 
