name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  AWS_REGION: eu-north-1

jobs:

  build:
    # runs-on: ubuntu-latest
    runs-on: [self-hosted]
    steps:
    - uses: actions/checkout@v3
    # - name: Build the Docker image
    #   run: docker build . --file Dockerfile --tag budget-tracker:$(date +%s)
    # - name: docker
    - name: Docker Compose
      run: docker-compose up -d --force-recreate --build
  # EC2-Deploy:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - id: deploy
  #       uses: bitovi/github-actions-deploy-docker-to-ec2@v0.5.0
  #       with:
  #         aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
  #         aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  #         aws_default_region: eu-north-1
  #         dot_env: ${{ secrets.DOT_ENV }}

  # deploy:
  #    name: Build and Push to ECR
  #    runs-on: ubuntu-latest
  #    steps:
  #    - name: Checkout
  #      uses: actions/checkout@v2
  #
  #    - name: Configure AWS credentials
  #      uses: aws-actions/configure-aws-credentials@v1
  #      with:
  #        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
  #        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  #        aws-region: ${{ env.AWS_REGION }}
  #
  #    - name: Login to Amazon ECR
  #      id: login-ecr
  #      uses: aws-actions/amazon-ecr-login@v1
  #
  #    # - name: Automatic Tagging of Releases
  #    #   id: increment-git-tag
  #    #   run: |
  #    #     bash ./build/git_update.sh -v major
  #
  #    - name: Build, Tag, and Push the Image to Amazon ECR
  #      id: build-image
  #      env:
  #        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
  #        ECR_REPOSITORY: hackathon-test
  #        IMAGE_TAG: latest
  #      run: |
  #        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
  #        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
